### PR TITLE
Updating to ox_lib.

### PR DESCRIPTION
**Pull request by KKasutaja**
I made some changes to the code by using ox_lib, and added a chance to use it with no ESX. I hope it is OK :)

### CODE REVIEW

**Comment by ohqpr** [comment]
Did you even test this? Your fork is throwing me errors.

**Comment by KKasutaja** [comment]
Hello, I replaced while loops with ox_lib's SetIntervals system, animations dictionaries are requested with ox_lib, and money check and payment is now going true ox_lib's callback system, also I changed the script to use nh-context's new version (https://github.com/nerohiro/nh-context). I was also searching a way for playing animations true ox_lib, but I didn't find it from the documentation, I think they only provide a way to request anim dict (https://overextended.github.io/docs/ox_lib/).

**Comment by ohqpr** [comment]
Your pushing updates without testing and leaving me to test it... This version is still broken. Load up FiveM and actually test your commits please. @KKasutaja

**Comment by KKasutaja** [comment]
Hey, resolved all issues and tested these previous problems, also updated old nh-context to new nh-context.

**Comment by KKasutaja** [comment]
What's wrong with it? I tested it and everything worked.

**Comment by ohqpr** [comment]
Impossible... I just downloaded your fork and got 5+ errors and nothing works... I don't know what you tested but it definitely wasn't your version.

**Comment by KKasutaja** [comment]
Can you post a picture of error please?

**Comment by KKasutaja** [comment]
> So how did you test and "everything worked" if you need the hash for the NPC to spawn? Without the has the NPC will not be there.

NPC is spawned with model, not hash
image

**Comment by ohqpr** [comment]
Well that just shows me you didn't actually test because you need the hash for the NPC to spawn. Yes the model is there but again the NPC wont be there without the hash, be my guest and load in game and test yourself.

**Comment by ohqpr** [comment]
image
Here is one example, NPC wont spawn until script is restarted.

**Comment by ohqpr** [comment]
image
Still cant receive treatment either, the menu just freezes on your screen.

**Comment by KKasutaja** [comment]
Do you have latest nh-context?

**Comment by ohqpr** [comment]
Dude yes.... Do you think I'm going to keep the same one after you explained you switched it and are using the latest? What do you think I'm a moron or something.

**Comment by ohqpr** [comment]
And by the way, keep the same context menu. DO NOT USE THE LATEST. Revert back. I'm not switching all my resources to use latest.

**Comment by KKasutaja** [comment]
Well, if you wan't to use that old context menu, then do it youself, I think im not going to contribute anymore as for me it works.

**Comment by ohqpr** [comment]
But your literally lying... Your fork doesn't work.. Show me that it works please then I will merge it.

**Comment by ohqpr** [comment]
@KKasutaja Can you show me a preview of your fork? Just make a little snippet and show that it works.

**Comment by ohqpr** [comment]
@KKasutaja message me on discord please qpr#7578

**Pull request closed without merging**
